image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script:
            - pip install boto3==1.3.0
            - pip install python-magic
            - python s3_delete.py docs.cgmonks.com
            - python s3_upload.py docs.cgmonks.com _build/html